# Generated by Django 5.2.3 on 2025-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_crear_grupos_permisos"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identification_number",
            field=models.CharField(
                blank=True,
                help_text="Número único de identificación del usuario (cédula, NIT, etc.)",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Número de Identificación",
            ),
        ),
    ]
