# Generated by Django 5.2.3 on 2025-07-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("nit", models.CharField(max_length=20, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("cell", models.CharField(max_length=12)),
                ("phone", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
