# Generated by Django 5.2.3 on 2025-07-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_company_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="nit",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
