# Generated by Django 5.2.3 on 2025-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_address_alter_company_nit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
