from rest_framework_simplejwt.views import TokenObtainPairView
from users.serializers.customTokenObtainPairSerializer import CustomTokenObtainPairSerialier

class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerialier